site_name: 2026考研笔记资料库
site_description: 11408及公共课复习知识库
site_author: Oyama Mahiro

docs_dir: 考研
site_url: https://oyama-mahiro-f.github.io/11408-notes-web/mkdocs/
site_dir: site/mkdocs

exclude_docs: |
  .git/
  .claude/
  .stfolder/
  site/
  mkdocs.yml
  requirements.txt
  **/*.pdf
  **/【课件】/**

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: 切换至深色模式
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: 切换至浅色模式

markdown_extensions:
  - meta
  - toc:
      permalink: true
  - md_in_html
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - sane_lists

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.min.js

nav:
- '408':
  - '概述': '408/index'
  - '操作系统':
    - '概述': '408/操作系统/index'
    - '第1章 计算机系统概述': '408/操作系统/笔记/第1章 计算机系统概述'
  - '数据结构':
    - '概述': '408/数据结构/index'
    - '作业': '408/数据结构/作业'
    - '第1章_绪论': '408/数据结构/笔记/第1章_绪论'
    - '第2章 线性表': '408/数据结构/笔记/第2章 线性表'
  - '计算机组成原理':
    - '概述': '408/计算机组成原理/index'
    - '第1章_计算机系统概述': '408/计算机组成原理/笔记/第1章_计算机系统概述'
    - '第2章 数据的表示和计算': '408/计算机组成原理/笔记/第2章 数据的表示和计算'
  - '计算机网络':
    - '概述': '408/计算机网络/index'
    - '第1章 计算机网络体系结构': '408/计算机网络/笔记/第1章 计算机网络体系结构'
    - '第2章 物理层': '408/计算机网络/笔记/第2章 物理层'
- '数学':
  - '概述': '数学/index'
  - '概率与统计':
    - '概述': '数学/概率与统计/index'
    - '第1章 随机事件和概率': '数学/概率与统计/第1章 随机事件和概率'
    - '第2章 三大概型': '数学/概率与统计/第2章 三大概型'
  - '线性代数':
    - '概述': '数学/线性代数/index'
    - '公式': '数学/线性代数/公式'
    - '第1章 行列式': '数学/线性代数/第1章 行列式'
    - '第2章 矩阵': '数学/线性代数/第2章 矩阵'
    - '第3章 向量': '数学/线性代数/第3章 向量'
    - '第4章 线性方程组': '数学/线性代数/第4章 线性方程组'
    - '第5章 矩阵的特征值和特征向量': '数学/线性代数/第5章 矩阵的特征值和特征向量'
  - '高数':
    - '概述': '数学/高数/index'
    - '公式总结': '数学/高数/公式总结'
    - '微分方程总结': '数学/高数/微分方程总结'
    - '第10章 无穷级数': '数学/高数/第10章 无穷级数'
    - '第11章 曲线积分': '数学/高数/第11章 曲线积分'
    - '第12章 曲面积分': '数学/高数/第12章 曲面积分'
    - '第1章 函数的极限与连续': '数学/高数/第1章 函数的极限与连续'
    - '第2章 一元函数微分学': '数学/高数/第2章 一元函数微分学'
    - '第3章 不定积分': '数学/高数/第3章 不定积分'
    - '第4章 定积分': '数学/高数/第4章 定积分'
    - '第5章 微分方程': '数学/高数/第5章 微分方程'
    - '第6章 向量代数与空间解析几何': '数学/高数/第6章 向量代数与空间解析几何'
    - '第7章 多元函数微分学': '数学/高数/第7章 多元函数微分学'
    - '第8章 二重积分': '数学/高数/第8章 二重积分'
    - '第9章 三重积分': '数学/高数/第9章 三重积分'
- '英语':
  - '概述': '英语/index'
  - '单词': '英语/单词'
